### ISSUE TITLE
DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.

### ISSUE THREAD

**Issue by bingohuang** [allencloud/daoker#10]
After I **Build** and **Install** daoker, it'll report error when I run `daoker ps` as follows.

`DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature`

My EVN:
* Linux VM_226_193_centos 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
* CentOS Linux release 7.1.1503 (Core)
* go version go1.6 linux/amd64
* docker 1.9.1

**Comment by bingoHuang** [comment]
Runing sucessful when I upgarde my docker to 1.11.2, but still show 
`DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/urfave/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature`
Whatever, it work. 👍
